# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-09 22:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('risk_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='risks.RiskType', verbose_name='Risk Type')),
            ],
            options={
                'verbose_name': 'Risk',
                'verbose_name_plural': 'Risks',
            },
        ),
    ]
